-- Parte 2

DROP SEQUENCE DELITOS_SEQ;
 
CREATE SEQUENCE DELITOS_SEQ MINVALUE 100 MAXVALUE 200 START WITH 100
    INCREMENT BY 1 NOCACHE;
    
CREATE SEQUENCE CAPTURAS_SEQ MINVALUE 1000 MAXVALUE 2000 START WITH 1000
    INCREMENT BY 1 NOCACHE;
    
-- Crear tablas
  CREATE TABLE "DELITOS" 
   (	
    "ID" INTEGER PRIMARY KEY, 
	"NOMBRES" VARCHAR2(255)
   ) ;
   
     CREATE TABLE "CAPTURAS" 
   (	
    "ID" INTEGER, 
    "FECHA" DATE,   
	"DEPARTAMENTO" VARCHAR2(255),
    "MUNICIPIO" VARCHAR2(255),
    "DIA" VARCHAR2(255),
    "BARRIO" VARCHAR2(255),
    "ZONA" VARCHAR2(255),
    "CLASE_SITIO" VARCHAR2(255),
    "EDAD" INTEGER,
    "SEXO" VARCHAR2(255),
    "ESTADO CIVIL" VARCHAR2(255),
    "CLASE_EMPLEADO" VARCHAR2(255),
    "PROFESION" VARCHAR2(255),
    "ESCOLARIDAD" VARCHAR2(255),
    "DELITO_ID" INTEGER,
     CONSTRAINT FK_DELITO_ID FOREIGN KEY(DELITO_ID) REFERENCES DELITOS(id)
   ) ;
   